# MedFocus PhD - App Engine Configuration (Alternativa ao Cloud Run)

runtime: nodejs20

# Instance class
instance_class: F2

# Automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Environment variables
env_variables:
  NODE_ENV: "production"
  PORT: "8080"

# Handlers
handlers:
  # Static files
  - url: /assets
    static_dir: dist/assets
    secure: always
    
  - url: /.*
    script: auto
    secure: always

# Health check
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
