# ─── MedFocus — Cloud Build Configuration ───────────────────
# Builds Docker image and deploys to Cloud Run

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/medfocus/medfocus-app:${_COMMIT_SHA}'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/medfocus/medfocus-app:latest'
      - '.'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/medfocus/medfocus-app:${_COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/medfocus/medfocus-app:latest'

  # Step 3: Deploy to Cloud Run (uses --update-env-vars to preserve existing vars like DATABASE_URL)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'medfocus-app'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/medfocus/medfocus-app:${_COMMIT_SHA}'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - 'viralgram-4-0-rodrigo:southamerica-east1:viralgram-mysql'
      - '--update-env-vars'
      - 'NODE_ENV=production,MP_ACCESS_TOKEN=APP_USR-3806961712774010-022816-a0067bac344e1badf6789ed35f4be39c-181888138,MP_PUBLIC_KEY=APP_USR-02d99962-9560-4686-8caf-d543bc235de8,MP_CLIENT_ID=3806961712774010,MP_CLIENT_SECRET=RLG14x1o6hZTiYUYLRSwShougvx0vC6B'

substitutions:
  _COMMIT_SHA: 'latest'

images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/medfocus/medfocus-app:${_COMMIT_SHA}'
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/medfocus/medfocus-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
