-- Guia de Doenças — Materiais com referências validadas
-- Colunas: id, title, description, content, libraryMaterialType, discipline, specialty, year, authorName, authorTitle, authorInstitution, source, doi, externalUrl, publishedYear, impactFactor, tags

-- CARDIOLOGIA
INSERT INTO library_materials (id, title, description, content, libraryMaterialType, discipline, specialty, year, authorName, authorTitle, authorInstitution, source, doi, externalUrl, publishedYear, impactFactor, tags, relevanceScore) VALUES
(UUID(), 'Hipertensão Arterial Sistêmica — Diagnóstico e Tratamento',
'Diretriz Brasileira de Hipertensão Arterial 2020. Classificação, metas e tratamento farmacológico.',
'CLASSIFICAÇÃO: Normal (<120/80), Elevada (120-129/<80), Estágio 1 (130-139/80-89), Estágio 2 (≥140/≥90), Crise (≥180/≥120). DIAGNÓSTICO: MRPA ou MAPA para confirmação. TRATAMENTO: MEV (redução de sódio, exercício, perda de peso) + farmacológico: IECA (enalapril, ramipril), BRA (losartana, valsartana), BCC (anlodipino), tiazídico (hidroclorotiazida, clortalidona). META: <130/80 para alto risco cardiovascular, <140/90 para risco habitual. ASSOCIAÇÕES: 2 fármacos se PA ≥160/100 ou risco alto. REFERÊNCIAS: Arq Bras Cardiol. 2021;116(3):516-658. DOI: 10.36660/abc.20201238. Mancia G et al. 2023 ESH Guidelines. J Hypertens. 2023;41(12):1874-2071.',
'guideline', 'Cardiologia', 'Cardiologia', 2021, 'Sociedade Brasileira de Cardiologia', 'Diretriz', 'SBC', 'Arquivos Brasileiros de Cardiologia', '10.36660/abc.20201238', 'https://www.scielo.br/j/abc/a/TLrgMhbkR7DSgJNvvJgFGBx/', 2021, '3.278', 'hipertensão,HAS,pressão arterial,IECA,BRA,anlodipino,anti-hipertensivo', 98),

(UUID(), 'Insuficiência Cardíaca — Classificação e Manejo Baseado em Evidências',
'Diretriz Brasileira de IC 2021. Pilares do tratamento da ICFEr e classificação funcional.',
'CLASSIFICAÇÃO: ICFEr (FEVE<40%), ICFEi (40-49%), ICFEp (≥50%). NYHA: I (sem limitação), II (limitação leve), III (limitação moderada), IV (sintomas em repouso). PILARES ICFEr: 1) IECA/ARNI (sacubitril-valsartana), 2) Betabloqueador (carvedilol, bisoprolol, metoprolol succinato), 3) Antagonista mineralocorticoide (espironolactona), 4) iSGLT2 (dapagliflozina, empagliflozina). ADICIONAR: hidralazina+nitrato se intolerância a IECA/BRA. Ivabradina se FC>70 em ritmo sinusal. REFERÊNCIAS: Arq Bras Cardiol. 2021;116(6):1174-1212. DOI: 10.36660/abc.20210062. McDonagh TA et al. 2021 ESC Guidelines for HF. Eur Heart J. 2021;42(36):3599-3726.',
'guideline', 'Cardiologia', 'Cardiologia', 2021, 'Sociedade Brasileira de Cardiologia', 'Diretriz', 'SBC', 'Arquivos Brasileiros de Cardiologia', '10.36660/abc.20210062', 'https://www.scielo.br/j/abc/', 2021, '3.278', 'insuficiência cardíaca,IC,FEVE,ARNI,sacubitril,iSGLT2,betabloqueador', 97),

(UUID(), 'Infarto Agudo do Miocárdio com Supra de ST (IAMCSST)',
'Guideline ACCF/AHA para manejo do IAMCSST. Reperfusão, antiagregação e cuidados pós-IAM.',
'DIAGNÓSTICO: Dor torácica >20min + supra ST ≥1mm em 2 derivações contíguas ou BRE novo + troponina elevada. TRATAMENTO IMEDIATO: AAS 300mg + clopidogrel 600mg (ou ticagrelor 180mg) + heparina + reperfusão. REPERFUSÃO: ICP primária <90min (porta-balão) — preferencial. Fibrinolítico <30min (porta-agulha) se ICP indisponível: tenecteplase ou alteplase. PÓS-IAM: AAS indefinido + P2Y12 por 12 meses + IECA + BB + estatina de alta potência (rosuvastatina 20-40mg ou atorvastatina 40-80mg). REFERÊNCIAS: O''Gara PT et al. 2013 ACCF/AHA STEMI Guideline. Circulation. 2013;127(4):e362-e425. PMID: 23247304. Ibanez B et al. 2017 ESC STEMI. Eur Heart J. 2018;39(2):119-177.',
'guideline', 'Cardiologia', 'Cardiologia', 2018, 'American Heart Association', 'Guideline', 'AHA/ACC/ESC', 'Circulation / European Heart Journal', '10.1161/CIR.0b013e3182742cf6', 'https://www.ahajournals.org/doi/10.1161/CIR.0b013e3182742cf6', 2018, '39.918', 'IAM,IAMCSST,infarto,supra ST,angioplastia,fibrinolítico,troponina,AAS', 99),

(UUID(), 'Fibrilação Atrial — Diagnóstico, Classificação e Anticoagulação',
'ESC Guidelines 2020 para manejo da FA. Estratificação de risco e escolha de anticoagulante.',
'DIAGNÓSTICO: ECG com ausência de ondas P + intervalos RR irregulares. CLASSIFICAÇÃO: Paroxística (<7 dias, autolimitada), Persistente (>7 dias ou cardioversão), Permanente (aceita). RISCO AVC: CHA₂DS₂-VASc ≥2 (homens) ou ≥3 (mulheres) → anticoagulação. RISCO SANGRAMENTO: HAS-BLED. ANTICOAGULANTES: DOACs preferidos (apixabana 5mg 2x/dia, rivaroxabana 20mg 1x/dia, dabigatrana 150mg 2x/dia, edoxabana 60mg 1x/dia). Varfarina se prótese mecânica ou estenose mitral moderada-grave. CONTROLE FC: BB ou BCC não-dihidropiridínico. CONTROLE RITMO: amiodarona, flecainida, ablação. REFERÊNCIAS: Hindricks G et al. 2020 ESC Guidelines for AF. Eur Heart J. 2021;42(5):373-498. PMID: 32860505.',
'guideline', 'Cardiologia', 'Cardiologia', 2021, 'European Society of Cardiology', 'Guideline', 'ESC', 'European Heart Journal', '10.1093/eurheartj/ehaa612', 'https://academic.oup.com/eurheartj/article/42/5/373/5899003', 2021, '39.3', 'fibrilação atrial,FA,anticoagulação,DOAC,apixabana,rivaroxabana,CHA2DS2-VASc', 97),

-- ENDOCRINOLOGIA
(UUID(), 'Diabetes Mellitus Tipo 2 — Diagnóstico e Algoritmo Terapêutico',
'Diretrizes SBD 2023-2024 e ADA Standards of Care 2024. Diagnóstico, metas e tratamento.',
'DIAGNÓSTICO: Glicemia jejum ≥126 mg/dL, HbA1c ≥6.5%, TOTG 2h ≥200 mg/dL, ou glicemia aleatória ≥200 + sintomas. Pré-diabetes: GJ 100-125, HbA1c 5.7-6.4%, TOTG 140-199. META: HbA1c <7% (individualizar: <6.5% se jovem sem comorbidades, <8% se idoso frágil). TRATAMENTO: 1ª linha: metformina 500-2000mg/dia. Se DCV aterosclerótica: + GLP-1RA (semaglutida, liraglutida) ou iSGLT2 (empagliflozina, dapagliflozina). Se DRC: + iSGLT2 (se TFG≥20) + finerenona. Se obesidade: + GLP-1RA ou tirzepatida. Se HbA1c >9%: considerar insulina. REFERÊNCIAS: Diretrizes SBD 2023-2024. ElSayed NA et al. ADA Standards of Care 2024. Diabetes Care. 2024;47(Suppl 1):S1-S321.',
'guideline', 'Endocrinologia', 'Endocrinologia', 2024, 'Sociedade Brasileira de Diabetes / ADA', 'Diretriz', 'SBD/ADA', 'Diabetes Care', '10.2337/dc24-SINT', 'https://diabetesjournals.org/care/issue/47/Supplement_1', 2024, '19.112', 'diabetes,DM2,metformina,iSGLT2,GLP-1,HbA1c,semaglutida,insulina', 99),

(UUID(), 'Cetoacidose Diabética — Protocolo de Emergência',
'Manejo da CAD na emergência. Hidratação, insulinoterapia e reposição eletrolítica.',
'CRITÉRIOS: Glicemia >250 mg/dL + pH <7.3 + bicarbonato <18 mEq/L + cetonemia/cetonúria positiva. GRAVIDADE: Leve (pH 7.25-7.30), Moderada (7.00-7.24), Grave (<7.00). TRATAMENTO: 1) HIDRATAÇÃO: SF 0.9% 1-1.5L na 1ª hora → 250-500mL/h. Se Na >145: trocar para NaCl 0.45%. 2) INSULINA: Regular 0.1 U/kg bolus + 0.1 U/kg/h EV contínua. Quando glicemia <200: reduzir para 0.02-0.05 U/kg/h + SG 5%. 3) POTÁSSIO: Se K <3.3 → repor antes da insulina (20-40 mEq/h). Se K 3.3-5.3 → 20-30 mEq/L no soro. Se K >5.3 → não repor, checar 2/2h. 4) BICARBONATO: apenas se pH <6.9 (100 mEq em 400mL). MONITORIZAÇÃO: Glicemia 1/1h, eletrólitos e gasometria 2-4h. REFERÊNCIAS: Kitabchi AE et al. Diabetes Care. 2009;32(7):1335-1343. PMID: 19564476. Umpierrez GE et al. Diabetologia. 2020;63(12):2453-2461.',
'guideline', 'Endocrinologia', 'Emergência', 2020, 'American Diabetes Association', 'Guideline', 'ADA', 'Diabetes Care / Diabetologia', '10.2337/dc09-9032', 'https://diabetesjournals.org/care/article/32/7/1335/27156', 2020, '19.112', 'CAD,cetoacidose,emergência,insulina,acidose metabólica,potássio', 98),

-- PNEUMOLOGIA
(UUID(), 'Pneumonia Adquirida na Comunidade — Diagnóstico e Antibioticoterapia',
'Diretrizes SBPT e ATS/IDSA para PAC. Estratificação CURB-65 e escolha antibiótica.',
'DIAGNÓSTICO: Sintomas (tosse, febre, dispneia, dor pleurítica) + infiltrado novo no RX tórax. ESTRATIFICAÇÃO CURB-65: C (confusão mental), U (ureia >50mg/dL), R (FR ≥30), B (PAS <90 ou PAD ≤60), 65 (idade ≥65). Score 0-1: ambulatorial; 2: considerar internação; 3-5: internação (4-5: UTI). TRATAMENTO AMBULATORIAL: Sem comorbidade → amoxicilina 1g 8/8h ou azitromicina 500mg/dia. Com comorbidade → amoxicilina-clavulanato 875mg 12/12h + azitromicina, ou levofloxacino 750mg/dia. INTERNADO (enfermaria): Ampicilina-sulbactam + azitromicina, ou levofloxacino. UTI: Ceftriaxona + azitromicina (ou levofloxacino). Se risco Pseudomonas: piperacilina-tazobactam + levofloxacino. DURAÇÃO: 5-7 dias (mínimo 5 dias, afebril >48h). REFERÊNCIAS: Corrêa RA et al. J Bras Pneumol. 2018;44(5):405-424. Metlay JP et al. ATS/IDSA 2019. Am J Respir Crit Care Med. 2019;200(7):e45-e67.',
'guideline', 'Pneumologia', 'Pneumologia', 2019, 'SBPT / ATS / IDSA', 'Diretriz', 'SBPT/ATS/IDSA', 'J Bras Pneumol / Am J Respir Crit Care Med', '10.1164/rccm.201908-1581ST', 'https://www.atsjournals.org/doi/10.1164/rccm.201908-1581ST', 2019, '30.528', 'pneumonia,PAC,CURB-65,antibiótico,amoxicilina,ceftriaxona,levofloxacino', 98),

(UUID(), 'DPOC — Diagnóstico, Classificação GOLD e Tratamento',
'GOLD Report 2024. Espirometria, classificação e escalonamento terapêutico.',
'DIAGNÓSTICO: Espirometria pós-broncodilatador: VEF1/CVF <0.70. CLASSIFICAÇÃO GOLD: 1 (leve, VEF1 ≥80%), 2 (moderado, 50-79%), 3 (grave, 30-49%), 4 (muito grave, <30%). GRUPOS ABE (2024): A (poucos sintomas, baixo risco exacerbação), B (mais sintomas), E (exacerbações ≥2/ano ou ≥1 com internação). TRATAMENTO: Grupo A → broncodilatador de curta duração SOS. Grupo B → LABA + LAMA. Grupo E → LABA + LAMA (+ ICS se eosinófilos ≥300). EXACERBAÇÃO: Prednisona 40mg 5 dias + antibiótico (amoxicilina-clavulanato ou azitromicina) se escarro purulento + broncodilatador de curta ação. REFERÊNCIAS: GOLD Report 2024. www.goldcopd.org. Agustí A et al. Am J Respir Crit Care Med. 2023;207(8):992-1012.',
'guideline', 'Pneumologia', 'Pneumologia', 2024, 'Global Initiative for COPD', 'Report', 'GOLD', 'Am J Respir Crit Care Med', '10.1164/rccm.202301-0106PP', 'https://goldcopd.org/2024-gold-report/', 2024, '30.528', 'DPOC,espirometria,LABA,LAMA,broncodilatador,GOLD,exacerbação', 97),

-- NEUROLOGIA
(UUID(), 'AVC Isquêmico — Diagnóstico, Trombólise e Trombectomia',
'AHA/ASA Guidelines 2019. Janela terapêutica, critérios e manejo agudo.',
'DIAGNÓSTICO: Déficit neurológico focal súbito + TC crânio sem hemorragia. NIHSS para quantificar gravidade. TROMBÓLISE: Alteplase 0.9 mg/kg (máx 90mg) EV — 10% bolus + 90% em 1h. Janela: <4.5h do início dos sintomas. Contraindicações: PA >185/110 não controlada, plaquetas <100.000, INR >1.7, glicemia <50. TROMBECTOMIA MECÂNICA: Oclusão de grande vaso (ACI, M1) + NIHSS ≥6 + ASPECTS ≥6. Janela: até 24h (com critérios de imagem DAWN/DEFUSE-3). CUIDADOS GERAIS: PA permissiva até 220/120 (se não trombolisou); controle glicemia 140-180; cabeceira 0-30°; profilaxia TVP. REFERÊNCIAS: Powers WJ et al. Stroke. 2019;50(12):e344-e418. PMID: 31662037. Nogueira RG et al. DAWN Trial. N Engl J Med. 2018;378(1):11-21.',
'guideline', 'Neurologia', 'Neurologia', 2019, 'AHA / ASA', 'Guideline', 'AHA/ASA', 'Stroke / N Engl J Med', '10.1161/STR.0000000000000211', 'https://www.ahajournals.org/doi/10.1161/STR.0000000000000211', 2019, '10.17', 'AVC,AVC isquêmico,trombólise,alteplase,NIHSS,trombectomia,DAWN', 99),

-- INFECTOLOGIA
(UUID(), 'Sepse e Choque Séptico — Surviving Sepsis Campaign 2021',
'Definição Sepsis-3, bundles de 1h e 3h, e manejo hemodinâmico.',
'DEFINIÇÃO SEPSIS-3: Infecção suspeita/confirmada + SOFA ≥2 pontos (ou aumento ≥2 do basal). qSOFA (triagem): FR ≥22, PAS ≤100, alteração mental (≥2 = alto risco). CHOQUE SÉPTICO: Sepse + necessidade de vasopressor para PAM ≥65 + lactato >2 mmol/L apesar de ressuscitação volêmica adequada. BUNDLE 1 HORA: 1) Medir lactato, 2) Hemoculturas antes do ATB, 3) Antibiótico de amplo espectro <1h, 4) Cristaloide 30 mL/kg se hipotensão ou lactato ≥4. BUNDLE 3 HORAS: Reavaliar volemia (USG point-of-care, elevação passiva de MMII). Se refratário: noradrenalina (1ª escolha) ± vasopressina. Se disfunção miocárdica: dobutamina. CORTICOIDE: Hidrocortisona 200mg/dia se choque refratário a vasopressor. REFERÊNCIAS: Singer M et al. Sepsis-3. JAMA. 2016;315(8):801-810. Evans L et al. SSC 2021. Intensive Care Med. 2021;47(11):1181-1247.',
'guideline', 'Infectologia', 'Emergência', 2021, 'SCCM / ESICM', 'Guideline', 'Surviving Sepsis Campaign', 'Intensive Care Med / JAMA', '10.1007/s00134-021-06506-y', 'https://link.springer.com/article/10.1007/s00134-021-06506-y', 2021, '41.787', 'sepse,choque séptico,SOFA,qSOFA,noradrenalina,antibiótico,lactato', 99),

-- GASTROENTEROLOGIA
(UUID(), 'Cirrose Hepática — Diagnóstico e Manejo das Complicações',
'EASL Guidelines. Child-Pugh, MELD e manejo de ascite, PBE, HDA e encefalopatia.',
'DIAGNÓSTICO: Clínico + laboratorial + imagem. Elastografia hepática: >12.5 kPa (fibrose avançada). CLASSIFICAÇÃO: Child-Pugh A (5-6), B (7-9), C (10-15). MELD: 3.78×ln(bilirrubina) + 11.2×ln(INR) + 9.57×ln(creatinina) + 6.43. COMPLICAÇÕES: 1) ASCITE: Paracentese diagnóstica (GASA ≥1.1 = hipertensão portal). Tratamento: restrição sódio + espironolactona 100-400mg + furosemida 40-160mg. Refratária: paracentese de alívio + albumina 8g/L. 2) PBE: PMN ≥250/mm³ no líquido ascítico → cefotaxima 2g 8/8h 5-7 dias + albumina (1.5g/kg D1, 1g/kg D3). 3) HDA VARICOSA: Terlipressina 2mg 4/4h + ligadura elástica + ATB profilático (ceftriaxona). 4) ENCEFALOPATIA: Lactulose 15-30mL 2-3x/dia (meta: 2-3 evacuações/dia) + rifaximina 550mg 12/12h. REFERÊNCIAS: EASL CPG Decompensated Cirrhosis. J Hepatol. 2018;69(2):406-460. PMID: 29653741.',
'guideline', 'Gastroenterologia', 'Gastroenterologia', 2018, 'European Association for the Study of the Liver', 'Guideline', 'EASL', 'Journal of Hepatology', '10.1016/j.jhep.2018.03.024', 'https://www.journal-of-hepatology.eu/', 2018, '30.083', 'cirrose,Child-Pugh,MELD,ascite,PBE,varizes,encefalopatia hepática,terlipressina', 98),

-- NEFROLOGIA
(UUID(), 'Doença Renal Crônica — Estadiamento KDIGO e Nefroproteção',
'KDIGO 2024 CKD Guideline. TFG, albuminúria, e estratégias de nefroproteção.',
'ESTADIAMENTO TFG: G1 (≥90), G2 (60-89), G3a (45-59), G3b (30-44), G4 (15-29), G5 (<15 ou diálise). ALBUMINÚRIA: A1 (<30 mg/g), A2 (30-300), A3 (>300). NEFROPROTEÇÃO: 1) IECA ou BRA (se albuminúria A2-A3), 2) iSGLT2 — dapagliflozina ou empagliflozina (se TFG ≥20), 3) Finerenona (se DM2 + albuminúria), 4) Controle PA <130/80, 5) Controle glicêmico (HbA1c <7%), 6) Estatina (se G3-G5). QUANDO ENCAMINHAR AO NEFROLOGISTA: TFG <30, albuminúria A3, queda TFG >5mL/min/ano, hipercalemia persistente. DIÁLISE: Indicar quando TFG <10-15 + sintomas urêmicos ou hipercalemia/hipervolemia refratárias. REFERÊNCIAS: KDIGO 2024 CKD Guideline. Kidney Int. 2024;105(4S):S117-S314. Heerspink HJL et al. DAPA-CKD. N Engl J Med. 2020;383(15):1436-1446.',
'guideline', 'Nefrologia', 'Nefrologia', 2024, 'KDIGO', 'Guideline', 'KDIGO', 'Kidney International', '10.1016/j.kint.2024.01.006', 'https://kdigo.org/guidelines/', 2024, '20.871', 'DRC,doença renal crônica,TFG,albuminúria,IECA,iSGLT2,diálise,finerenona', 98),

-- EMERGÊNCIA
(UUID(), 'Parada Cardiorrespiratória — ACLS 2020',
'Algoritmo AHA de ACLS. RCP de alta qualidade, desfibrilação e drogas.',
'ALGORITMO C-A-B: 1) COMPRESSÕES: 100-120/min, profundidade 5-6cm, retorno completo do tórax, minimizar interrupções (<10s). 2) VIA AÉREA: IOT ou dispositivo supraglótico. 3) VENTILAÇÃO: 10/min após via aérea avançada. RITMOS CHOCÁVEIS (FV/TV sem pulso): Desfibrilação bifásica 200J → RCP 2min → epinefrina 1mg EV a cada 3-5min → choque → amiodarona 300mg (1ª dose), 150mg (2ª dose). RITMOS NÃO CHOCÁVEIS (assistolia/AESP): Epinefrina 1mg imediata → RCP 2min → tratar causas reversíveis. 5H: Hipovolemia, Hipóxia, H+ (acidose), Hipo/Hipercalemia, Hipotermia. 5T: Tensão (pneumotórax), Tamponamento, Toxinas, TEP, Trombose coronariana. PÓS-PCR: Controle temperatura alvo 32-36°C por 24h, ICP se IAMCSST, TC crânio. REFERÊNCIAS: Panchal AR et al. 2020 AHA ACLS. Circulation. 2020;142(16_suppl_2):S366-S468. PMID: 33081529.',
'guideline', 'Emergência', 'Emergência', 2020, 'American Heart Association', 'Guideline', 'AHA', 'Circulation', '10.1161/CIR.0000000000000916', 'https://www.ahajournals.org/doi/10.1161/CIR.0000000000000916', 2020, '39.918', 'PCR,ACLS,RCP,desfibrilação,epinefrina,amiodarona,FV,assistolia', 99),

-- REUMATOLOGIA
(UUID(), 'Artrite Reumatoide — Diagnóstico ACR/EULAR e Tratamento',
'Critérios classificatórios 2010 e guideline ACR 2021 para tratamento.',
'DIAGNÓSTICO: Critérios ACR/EULAR 2010 (≥6/10 pontos): articulações acometidas (0-5), sorologia FR/anti-CCP (0-3), reagentes de fase aguda PCR/VHS (0-1), duração ≥6 semanas (0-1). TRATAMENTO: 1ª LINHA: Metotrexato 15-25mg/semana VO ou SC + ácido fólico 5mg/semana. Se intolerância: leflunomida 20mg/dia. DMARD BIOLÓGICO (se refratário em 3-6 meses): Anti-TNF (adalimumabe, etanercepte, infliximabe), Anti-IL6 (tocilizumabe), Anti-CD20 (rituximabe), CTLA4-Ig (abatacepte). JAK INIBIDORES: Tofacitinibe, baricitinibe, upadacitinibe. META: Remissão (DAS28 <2.6) ou baixa atividade (DAS28 <3.2). MONITORAR: Hemograma, TGO/TGP, creatinina a cada 3 meses. REFERÊNCIAS: Aletaha D et al. Ann Rheum Dis. 2010;69(9):1580-1588. Fraenkel L et al. Arthritis Rheumatol. 2021;73(7):1108-1123.',
'guideline', 'Reumatologia', 'Reumatologia', 2021, 'ACR / EULAR', 'Guideline', 'ACR/EULAR', 'Arthritis & Rheumatology', '10.1002/art.41752', 'https://onlinelibrary.wiley.com/doi/10.1002/art.41752', 2021, '13.3', 'artrite reumatoide,metotrexato,anti-TNF,biológico,DAS28,anti-CCP', 97),

-- PEDIATRIA
(UUID(), 'Bronquiolite Viral Aguda — Manejo em Lactentes',
'AAP Clinical Practice Guideline. Diagnóstico clínico e tratamento de suporte.',
'ETIOLOGIA: VSR (vírus sincicial respiratório) — principal agente. Outros: rinovírus, metapneumovírus, parainfluenza. EPIDEMIOLOGIA: Pico no inverno, lactentes <2 anos (maior gravidade <6 meses). DIAGNÓSTICO: CLÍNICO — coriza → tosse → sibilância + taquipneia + tiragem + crepitações. RX tórax: hiperinsuflação, atelectasias. NÃO é necessário de rotina. TRATAMENTO: SUPORTE — 1) O2 suplementar se SpO2 <90% persistente, 2) Hidratação (VO ou EV se não tolerar), 3) Aspiração nasal suave. NÃO USAR de rotina: broncodilatador (beta-2), corticoide, antibiótico, solução salina hipertônica nebulizada. INTERNAÇÃO: SpO2 <90%, desidratação, apneia, prematuridade <32 semanas. PREVENÇÃO: Palivizumabe (anti-VSR) para prematuros <29 semanas e cardiopatas/pneumopatas. Nirsevimabe (dose única) aprovado 2023. REFERÊNCIAS: Ralston SL et al. Pediatrics. 2014;134(5):e1474-e1502. PMID: 25349312. AAP 2023 Update.',
'guideline', 'Pediatria', 'Pediatria', 2023, 'American Academy of Pediatrics', 'Guideline', 'AAP', 'Pediatrics', '10.1542/peds.2014-2742', 'https://publications.aap.org/pediatrics/article/134/5/e1474/33150', 2023, '8.64', 'bronquiolite,VSR,lactente,sibilância,pediatria,palivizumabe,nirsevimabe', 97),

-- GINECOLOGIA/OBSTETRÍCIA
(UUID(), 'Pré-Eclâmpsia — Diagnóstico, Classificação e Manejo',
'ACOG Practice Bulletin. Critérios diagnósticos, prevenção e tratamento.',
'DIAGNÓSTICO: PA ≥140/90 mmHg após 20 semanas de gestação + proteinúria ≥300mg/24h (ou relação P/C ≥0.3) OU sinais de gravidade sem proteinúria. SINAIS DE GRAVIDADE: PA ≥160/110, plaquetas <100.000, creatinina >1.1, transaminases 2x LSN, edema pulmonar, sintomas cerebrais (cefaleia intensa, escotomas) ou dor epigástrica. HELLP: Hemólise + Elevated Liver enzymes + Low Platelets. PREVENÇÃO: AAS 100-150mg/dia a partir de 12-16 semanas se alto risco. TRATAMENTO: 1) SULFATO DE MAGNÉSIO (prevenção eclâmpsia): Zuspan — 4g EV em 20min + 1-2g/h manutenção. Monitorar: reflexo patelar, FR >12, diurese >25mL/h. Antídoto: gluconato de cálcio 1g EV. 2) ANTI-HIPERTENSIVO: Nifedipino 10-20mg VO (1ª escolha), hidralazina 5mg EV, labetalol 20mg EV. 3) PARTO: ≥37 semanas (sem gravidade) ou imediato se grave/HELLP/eclâmpsia. REFERÊNCIAS: ACOG Practice Bulletin 222. Obstet Gynecol. 2020;135(6):e237-e260. PMID: 32443079. Rolnik DL et al. ASPRE Trial. N Engl J Med. 2017;377(7):613-622.',
'guideline', 'Ginecologia', 'Obstetrícia', 2020, 'ACOG', 'Practice Bulletin', 'ACOG', 'Obstetrics & Gynecology', '10.1097/AOG.0000000000003891', 'https://journals.lww.com/greenjournal/', 2020, '7.661', 'pré-eclâmpsia,eclâmpsia,sulfato de magnésio,HELLP,gestação,AAS,nifedipino', 98),

-- PSIQUIATRIA
(UUID(), 'Depressão Maior — Diagnóstico DSM-5 e Farmacoterapia',
'APA Practice Guidelines. Critérios diagnósticos, triagem e algoritmo de tratamento.',
'DIAGNÓSTICO DSM-5: ≥5 sintomas por ≥2 semanas (obrigatório: humor deprimido OU anedonia): 1) Humor deprimido, 2) Anedonia, 3) Alteração peso/apetite, 4) Insônia/hipersonia, 5) Agitação/retardo psicomotor, 6) Fadiga, 7) Culpa/inutilidade, 8) Dificuldade concentração, 9) Ideação suicida. TRIAGEM: PHQ-9 (≥10 = depressão moderada, ≥20 = grave). TRATAMENTO: 1ª LINHA ISRS: Sertralina 50-200mg, escitalopram 10-20mg, fluoxetina 20-60mg. 2ª LINHA IRSN: Venlafaxina 75-225mg, duloxetina 60-120mg. ATÍPICOS: Bupropiona 150-300mg (se fadiga/tabagismo), mirtazapina 15-45mg (se insônia/inapetência). REFRATÁRIA: Associar lítio, aripiprazol, ou trocar classe. ECT se grave/refratária. DURAÇÃO: Primeiro episódio: 6-12 meses após remissão. Recorrente: ≥2 anos ou indefinido. REFERÊNCIAS: APA Practice Guidelines 2023. Cipriani A et al. Lancet. 2018;391(10128):1357-1366. PMID: 29477251.',
'guideline', 'Psiquiatria', 'Psiquiatria', 2023, 'American Psychiatric Association', 'Practice Guideline', 'APA', 'Am J Psychiatry / Lancet', '10.1016/S0140-6736(17)32802-7', 'https://psychiatryonline.org/guidelines', 2023, '18.112', 'depressão,ISRS,sertralina,escitalopram,PHQ-9,antidepressivo,DSM-5', 97);
