-- Guia de Doenças — Materiais com referências validadas
-- Inserção de doenças por especialidade com referências de Harrison's, Cecil, UpToDate, SBC, SBD, etc.

-- CARDIOLOGIA
INSERT INTO library_materials (id, title, author, discipline, type, description, url, year, tags, citationCount, impactFactor, createdAt) VALUES
(UUID(), 'Hipertensão Arterial Sistêmica — Diagnóstico e Tratamento', 'Sociedade Brasileira de Cardiologia (SBC)', 'Cardiologia', 'guideline', 'Diretriz Brasileira de Hipertensão Arterial 2020. Classificação: Normal (<120/80), Elevada (120-129/<80), Estágio 1 (130-139/80-89), Estágio 2 (≥140/≥90). Tratamento: MEV + IECA/BRA, BCC ou tiazídico. Meta: <130/80 para alto risco. Ref: Arq Bras Cardiol. 2021;116(3):516-658. DOI: 10.36660/abc.20201238', 'https://www.scielo.br/j/abc/a/TLrgMhbkR7DSgJNvvJgFGBx/', 2021, 'hipertensão,HAS,pressão arterial,anti-hipertensivo,IECA,BRA', 450, 3.278, NOW()),

(UUID(), 'Insuficiência Cardíaca — Classificação e Manejo', 'Sociedade Brasileira de Cardiologia (SBC)', 'Cardiologia', 'guideline', 'Diretriz Brasileira de IC 2021. Classificação: ICFEr (FEVE<40%), ICFEi (40-49%), ICFEp (≥50%). Tratamento ICFEr: IECA/ARNI + BB + espironolactona + iSGLT2 (pilares). NYHA I-IV. Ref: Arq Bras Cardiol. 2021;116(6):1174-1212. DOI: 10.36660/abc.20210062', 'https://www.scielo.br/j/abc/', 2021, 'insuficiência cardíaca,IC,FEVE,ARNI,sacubitril,iSGLT2', 380, 3.278, NOW()),

(UUID(), 'Infarto Agudo do Miocárdio com Supradesnivelamento de ST (IAMCSST)', 'American Heart Association (AHA)', 'Cardiologia', 'guideline', 'Diagnóstico: dor torácica + supra ST ≥1mm em 2 derivações contíguas ou BRE novo. Tratamento: AAS + P2Y12 + heparina + reperfusão (ICP primária <90min ou fibrinolítico <30min). Ref: O''Gara PT et al. 2013 ACCF/AHA STEMI Guideline. Circulation. 2013;127(4):e362-e425. PMID: 23247304', 'https://www.ahajournals.org/doi/10.1161/CIR.0b013e3182742cf6', 2013, 'IAM,IAMCSST,infarto,supra ST,angioplastia,fibrinolítico', 2500, 39.918, NOW()),

(UUID(), 'Fibrilação Atrial — Diagnóstico e Anticoagulação', 'European Society of Cardiology (ESC)', 'Cardiologia', 'guideline', 'FA: arritmia sustentada mais comum. Diagnóstico: ECG com ausência de ondas P e intervalos RR irregulares. Classificação: paroxística, persistente, permanente. Anticoagulação: CHA₂DS₂-VASc ≥2 (homens) ou ≥3 (mulheres) → DOAC. Ref: Hindricks G et al. 2020 ESC Guidelines for AF. Eur Heart J. 2021;42(5):373-498. PMID: 32860505', 'https://academic.oup.com/eurheartj/article/42/5/373/5899003', 2021, 'fibrilação atrial,FA,anticoagulação,DOAC,CHA2DS2-VASc', 1800, 39.3, NOW()),

(UUID(), 'Síndrome Coronariana Aguda sem Supra de ST (SCASSST)', 'Sociedade Brasileira de Cardiologia (SBC)', 'Cardiologia', 'guideline', 'Inclui angina instável e IAMSSST. Diagnóstico: dor torácica + troponina elevada (IAMSSST) ou normal (AI). Estratificação: GRACE score. Tratamento: dupla antiagregação + anticoagulação + estratégia invasiva precoce se alto risco. Ref: Nicolau JC et al. Arq Bras Cardiol. 2021;117(1):181-264. DOI: 10.36660/abc.20210180', 'https://www.scielo.br/j/abc/', 2021, 'SCA,SCASSST,angina instável,troponina,GRACE', 320, 3.278, NOW()),

-- ENDOCRINOLOGIA
(UUID(), 'Diabetes Mellitus Tipo 2 — Diagnóstico e Tratamento', 'Sociedade Brasileira de Diabetes (SBD)', 'Endocrinologia', 'guideline', 'Diagnóstico: glicemia jejum ≥126, HbA1c ≥6.5%, TOTG ≥200, ou glicemia aleatória ≥200 + sintomas. Tratamento: metformina 1ª linha + iSGLT2 ou GLP-1RA se DCV/DRC. Meta HbA1c <7% (individualizar). Ref: Diretrizes SBD 2023-2024. ISBN: 978-65-5941-622-6', 'https://diretriz.diabetes.org.br/', 2023, 'diabetes,DM2,metformina,iSGLT2,GLP-1,HbA1c', 500, 2.8, NOW()),

(UUID(), 'Cetoacidose Diabética (CAD) — Manejo na Emergência', 'American Diabetes Association (ADA)', 'Endocrinologia', 'guideline', 'Critérios: glicemia >250, pH <7.3, bicarbonato <18, cetonemia/cetonúria. Tratamento: SF 0.9% 1-1.5L/h → insulina regular 0.1U/kg/h EV → reposição K+ (se <5.3). Monitorar: glicemia 1/1h, gasometria 2/2h. Ref: Kitabchi AE et al. Diabetes Care. 2009;32(7):1335-1343. PMID: 19564476', 'https://diabetesjournals.org/care/article/32/7/1335/27156', 2009, 'CAD,cetoacidose,emergência,insulina,acidose metabólica', 1200, 19.112, NOW()),

(UUID(), 'Hipotireoidismo — Diagnóstico e Reposição Hormonal', 'American Thyroid Association (ATA)', 'Endocrinologia', 'guideline', 'Diagnóstico: TSH elevado + T4L baixo (primário). Subclínico: TSH elevado + T4L normal. Tratamento: levotiroxina 1.6 mcg/kg/dia em jejum. Monitorar TSH em 6-8 semanas. Ref: Jonklaas J et al. Thyroid. 2014;24(12):1670-1751. PMID: 25266247', 'https://www.liebertpub.com/doi/10.1089/thy.2014.0028', 2014, 'hipotireoidismo,TSH,T4,levotiroxina,tireoide', 900, 6.568, NOW()),

-- PNEUMOLOGIA
(UUID(), 'Pneumonia Adquirida na Comunidade (PAC) — Diagnóstico e Tratamento', 'Sociedade Brasileira de Pneumologia e Tisiologia (SBPT)', 'Pneumologia', 'guideline', 'Diagnóstico: quadro clínico + RX tórax com infiltrado. Estratificação: CURB-65 (0-1: ambulatorial, 2: internação, 3-5: UTI). Tratamento ambulatorial: amoxicilina ou azitromicina. Internado: amoxicilina-clavulanato + azitromicina ou levofloxacino. Ref: Corrêa RA et al. J Bras Pneumol. 2018;44(5):405-424. PMID: 30517389', 'https://www.jornaldepneumologia.com.br/', 2018, 'pneumonia,PAC,CURB-65,antibiótico,amoxicilina', 280, 2.935, NOW()),

(UUID(), 'DPOC — Diagnóstico e Tratamento Estável', 'Global Initiative for Chronic Obstructive Lung Disease (GOLD)', 'Pneumologia', 'guideline', 'Diagnóstico: espirometria VEF1/CVF <0.7 pós-BD. Classificação GOLD: 1 (leve VEF1≥80%), 2 (moderado 50-79%), 3 (grave 30-49%), 4 (muito grave <30%). Grupos ABE. Tratamento: LABA + LAMA ± ICS. Ref: GOLD Report 2024. www.goldcopd.org', 'https://goldcopd.org/2024-gold-report/', 2024, 'DPOC,espirometria,LABA,LAMA,broncodilatador,GOLD', 5000, 0, NOW()),

(UUID(), 'Asma — Diagnóstico e Tratamento por Steps', 'Global Initiative for Asthma (GINA)', 'Pneumologia', 'guideline', 'Diagnóstico: sintomas variáveis + limitação ao fluxo aéreo variável (espirometria com BD positivo ≥12% e 200mL). Steps GINA 2024: Step 1-2: CI-formoterol SOS; Step 3: CI dose baixa + LABA; Step 4: CI dose média + LABA; Step 5: CI dose alta + LABA + anti-IgE/IL5. Ref: GINA Report 2024. www.ginasthma.org', 'https://ginasthma.org/gina-reports/', 2024, 'asma,GINA,corticoide inalatório,LABA,broncoespasmo', 4500, 0, NOW()),

-- NEUROLOGIA
(UUID(), 'AVC Isquêmico — Diagnóstico e Trombólise', 'American Heart Association / American Stroke Association', 'Neurologia', 'guideline', 'Diagnóstico: déficit neurológico focal súbito + TC sem hemorragia. NIHSS para gravidade. Trombólise: alteplase 0.9mg/kg (máx 90mg) EV se <4.5h do início. Trombectomia mecânica se oclusão de grande vaso <24h. Ref: Powers WJ et al. Stroke. 2019;50(12):e344-e418. PMID: 31662037', 'https://www.ahajournals.org/doi/10.1161/STR.0000000000000211', 2019, 'AVC,AVC isquêmico,trombólise,alteplase,NIHSS,trombectomia', 2000, 10.17, NOW()),

(UUID(), 'Epilepsia — Diagnóstico e Tratamento com Antiepilépticos', 'International League Against Epilepsy (ILAE)', 'Neurologia', 'guideline', 'Diagnóstico: ≥2 crises não provocadas com intervalo >24h, ou 1 crise + risco >60% de recorrência. Classificação: focal, generalizada, desconhecida. 1ª linha focal: carbamazepina, lamotrigina, levetiracetam. 1ª linha generalizada: valproato, lamotrigina, levetiracetam. Ref: Scheffer IE et al. Epilepsia. 2017;58(4):512-521. PMID: 28276062', 'https://onlinelibrary.wiley.com/doi/10.1111/epi.13709', 2017, 'epilepsia,crise convulsiva,antiepiléptico,carbamazepina,valproato', 1500, 6.04, NOW()),

-- INFECTOLOGIA
(UUID(), 'Sepse e Choque Séptico — Sepsis-3', 'Society of Critical Care Medicine (SCCM)', 'Infectologia', 'guideline', 'Definição Sepsis-3: infecção + SOFA ≥2 pontos. Choque séptico: sepse + vasopressor para PAM ≥65 + lactato >2 mmol/L. Tratamento: antibiótico <1h + cristaloide 30mL/kg em 3h + noradrenalina se refratário. Surviving Sepsis Campaign 2021. Ref: Evans L et al. Intensive Care Med. 2021;47(11):1181-1247. PMID: 34599691', 'https://link.springer.com/article/10.1007/s00134-021-06506-y', 2021, 'sepse,choque séptico,SOFA,qSOFA,noradrenalina,antibiótico', 3000, 41.787, NOW()),

(UUID(), 'HIV/AIDS — Diagnóstico e Terapia Antirretroviral (TARV)', 'Ministério da Saúde do Brasil', 'Infectologia', 'guideline', 'Diagnóstico: teste rápido + confirmatório. Iniciar TARV para todos os PVHIV, independente de CD4. Esquema preferencial: TDF + 3TC + DTG. Monitorar: CV e CD4 a cada 6 meses. Profilaxias: CD4<200 → SMX-TMP (PCP); CD4<50 → azitromicina (MAC). Ref: PCDT HIV/AIDS 2024. Ministério da Saúde.', 'https://www.gov.br/aids/pt-br', 2024, 'HIV,AIDS,TARV,antirretroviral,dolutegravir,CD4', 600, 0, NOW()),

-- GASTROENTEROLOGIA
(UUID(), 'Doença do Refluxo Gastroesofágico (DRGE)', 'American College of Gastroenterology (ACG)', 'Gastroenterologia', 'guideline', 'Diagnóstico: sintomas típicos (pirose, regurgitação) + resposta ao IBP. EDA se sinais de alarme. Tratamento: IBP dose padrão 4-8 semanas. Manutenção: dose mínima eficaz. Barrett: vigilância endoscópica. Ref: Katz PO et al. Am J Gastroenterol. 2022;117(1):27-56. PMID: 34807007', 'https://journals.lww.com/ajg/', 2022, 'DRGE,refluxo,IBP,omeprazol,esôfago de Barrett', 800, 12.045, NOW()),

(UUID(), 'Cirrose Hepática — Diagnóstico e Complicações', 'European Association for the Study of the Liver (EASL)', 'Gastroenterologia', 'guideline', 'Diagnóstico: clínico + laboratorial + imagem (elastografia >12.5 kPa). Classificação: Child-Pugh (A/B/C) e MELD. Complicações: ascite (espironolactona + furosemida), PBE (cefotaxima), HDA varicosa (terlipressina + ligadura), encefalopatia (lactulose + rifaximina). Ref: EASL CPG Decompensated Cirrhosis. J Hepatol. 2018;69(2):406-460. PMID: 29653741', 'https://www.journal-of-hepatology.eu/', 2018, 'cirrose,Child-Pugh,MELD,ascite,varizes,encefalopatia hepática', 1100, 30.083, NOW()),

-- NEFROLOGIA
(UUID(), 'Doença Renal Crônica (DRC) — Estadiamento e Manejo', 'Kidney Disease: Improving Global Outcomes (KDIGO)', 'Nefrologia', 'guideline', 'Estadiamento: G1 (TFG≥90), G2 (60-89), G3a (45-59), G3b (30-44), G4 (15-29), G5 (<15 ou diálise). Albuminúria: A1 (<30), A2 (30-300), A3 (>300 mg/g). Tratamento: IECA/BRA + iSGLT2 (se TFG≥20) + controle PA <130/80. Ref: KDIGO 2024 CKD Guideline. Kidney Int. 2024;105(4S):S117-S314.', 'https://kdigo.org/guidelines/', 2024, 'DRC,doença renal crônica,TFG,albuminúria,IECA,iSGLT2,diálise', 2000, 20.871, NOW()),

(UUID(), 'Injúria Renal Aguda (IRA) — Diagnóstico e Manejo', 'KDIGO', 'Nefrologia', 'guideline', 'Critérios KDIGO: aumento Cr ≥0.3 em 48h, ou ≥1.5x basal em 7 dias, ou diurese <0.5mL/kg/h por 6h. Estágios: 1 (Cr 1.5-1.9x), 2 (2.0-2.9x), 3 (≥3x ou Cr≥4 ou diálise). Causas: pré-renal (hipovolemia), renal (NTA), pós-renal (obstrução). Ref: KDIGO AKI Guideline. Kidney Int Suppl. 2012;2(1):1-138.', 'https://kdigo.org/guidelines/acute-kidney-injury/', 2012, 'IRA,injúria renal aguda,creatinina,diálise,NTA', 3500, 20.871, NOW()),

-- REUMATOLOGIA
(UUID(), 'Artrite Reumatoide — Diagnóstico e Tratamento', 'American College of Rheumatology (ACR)', 'Reumatologia', 'guideline', 'Diagnóstico: critérios ACR/EULAR 2010 (≥6 pontos). Tratamento: metotrexato 1ª linha (15-25mg/semana) + ácido fólico. Se refratário: associar biológico (anti-TNF, anti-IL6, anti-CD20) ou JAKi. Meta: remissão ou baixa atividade (DAS28 <3.2). Ref: Fraenkel L et al. Arthritis Rheumatol. 2021;73(7):1108-1123. PMID: 34101387', 'https://onlinelibrary.wiley.com/doi/10.1002/art.41752', 2021, 'artrite reumatoide,metotrexato,anti-TNF,biológico,DAS28', 700, 13.3, NOW()),

(UUID(), 'Lúpus Eritematoso Sistêmico (LES) — Diagnóstico e Tratamento', 'European Alliance of Associations for Rheumatology (EULAR)', 'Reumatologia', 'guideline', 'Diagnóstico: critérios EULAR/ACR 2019 (≥10 pontos + ANA positivo). Tratamento: hidroxicloroquina para todos + corticoide (dose mínima) + imunossupressor conforme manifestação (nefrite: micofenolato ou ciclofosfamida). Ref: Fanouriakis A et al. Ann Rheum Dis. 2019;78(6):736-745. PMID: 30926722', 'https://ard.bmj.com/content/78/6/736', 2019, 'lúpus,LES,ANA,hidroxicloroquina,nefrite lúpica', 1000, 27.973, NOW()),

-- HEMATOLOGIA
(UUID(), 'Anemia Ferropriva — Diagnóstico e Reposição de Ferro', 'British Society for Haematology (BSH)', 'Hematologia', 'guideline', 'Diagnóstico: Hb baixa + ferritina <30 ng/mL (ou <100 se DRC/IC) + saturação transferrina <20%. Tratamento oral: sulfato ferroso 200mg 2-3x/dia (60-200mg Fe elementar/dia). EV: carboximaltose férrica 15mg/kg (máx 1000mg) se intolerância oral ou má absorção. Ref: Snook J et al. Br J Haematol. 2021;195(2):208-227. PMID: 34490624', 'https://onlinelibrary.wiley.com/doi/10.1111/bjh.17848', 2021, 'anemia,ferropriva,ferritina,ferro,sulfato ferroso', 400, 6.998, NOW()),

-- PEDIATRIA
(UUID(), 'Bronquiolite Viral Aguda em Lactentes', 'American Academy of Pediatrics (AAP)', 'Pediatria', 'guideline', 'Etiologia: VSR (principal). Diagnóstico: clínico (sibilância + taquipneia + tiragem em <2 anos). Tratamento: suporte (O2 se SpO2<90%, hidratação, aspiração nasal). NÃO usar: broncodilatador, corticoide, antibiótico de rotina. Ref: Ralston SL et al. Pediatrics. 2014;134(5):e1474-e1502. PMID: 25349312', 'https://publications.aap.org/pediatrics/article/134/5/e1474/33150', 2014, 'bronquiolite,VSR,lactente,sibilância,pediatria', 1500, 8.64, NOW()),

(UUID(), 'Infecção do Trato Urinário (ITU) na Infância', 'National Institute for Health and Care Excellence (NICE)', 'Pediatria', 'guideline', 'Diagnóstico: EAS + urocultura (>100.000 UFC/mL). Tratamento: <3 meses → ampicilina + gentamicina EV; >3 meses não complicada → cefalexina ou SMX-TMP VO 7-10 dias. Investigação: USG renal para todos; UCM se ITU febril recorrente. Ref: NICE CG54. UTI in under 16s. 2022 update.', 'https://www.nice.org.uk/guidance/cg54', 2022, 'ITU,infecção urinária,pediatria,urocultura,refluxo vesicoureteral', 600, 0, NOW()),

-- GINECOLOGIA/OBSTETRÍCIA
(UUID(), 'Pré-Eclâmpsia — Diagnóstico e Manejo', 'American College of Obstetricians and Gynecologists (ACOG)', 'Ginecologia', 'guideline', 'Diagnóstico: PA ≥140/90 após 20 semanas + proteinúria ≥300mg/24h ou relação P/C ≥0.3. Grave: PA ≥160/110, plaquetas <100.000, Cr >1.1, transaminases 2x, edema pulmonar, sintomas cerebrais/visuais. Tratamento: sulfato de magnésio (Zuspan: 4g EV + 1-2g/h) + anti-hipertensivo (nifedipino, hidralazina). Parto: ≥37 sem ou se grave. Ref: ACOG Practice Bulletin 222. Obstet Gynecol. 2020;135(6):e237-e260. PMID: 32443079', 'https://journals.lww.com/greenjournal/', 2020, 'pré-eclâmpsia,eclâmpsia,sulfato de magnésio,gestação,hipertensão gestacional', 1800, 7.661, NOW()),

-- PSIQUIATRIA
(UUID(), 'Depressão Maior — Diagnóstico e Tratamento Farmacológico', 'American Psychiatric Association (APA)', 'Psiquiatria', 'guideline', 'Diagnóstico: DSM-5 — ≥5 sintomas por ≥2 semanas (humor deprimido ou anedonia obrigatório). PHQ-9 para triagem. 1ª linha: ISRS (sertralina, escitalopram, fluoxetina). 2ª linha: IRSN (venlafaxina, duloxetina). Duração: 6-12 meses após remissão. Ref: APA Practice Guidelines 2023. Am J Psychiatry.', 'https://psychiatryonline.org/guidelines', 2023, 'depressão,ISRS,sertralina,escitalopram,PHQ-9,antidepressivo', 900, 18.112, NOW()),

-- DERMATOLOGIA
(UUID(), 'Dermatite Atópica — Diagnóstico e Tratamento', 'European Academy of Dermatology and Venereology (EADV)', 'Dermatologia', 'guideline', 'Diagnóstico: critérios de Hanifin & Rajka. Prurido + eczema crônico/recorrente + história pessoal/familiar de atopia. Tratamento: emolientes + corticoide tópico (leve: hidrocortisona; moderado: mometasona; grave: clobetasol). Refratário: tacrolimus tópico, dupilumabe SC. Ref: Wollenberg A et al. J Eur Acad Dermatol Venereol. 2022;36(9):1409-1431. PMID: 35980214', 'https://onlinelibrary.wiley.com/doi/10.1111/jdv.18345', 2022, 'dermatite atópica,eczema,corticoide tópico,dupilumabe,emoliente', 500, 9.228, NOW()),

-- ORTOPEDIA
(UUID(), 'Fraturas do Fêmur Proximal — Diagnóstico e Tratamento Cirúrgico', 'American Academy of Orthopaedic Surgeons (AAOS)', 'Ortopedia', 'guideline', 'Classificação: intracapsulares (colo femoral — Garden I-IV) e extracapsulares (transtrocantéricas — AO/OTA). Tratamento: Garden I-II → fixação interna (parafusos canulados); Garden III-IV em idosos → artroplastia (parcial ou total). Transtrocantérica → haste cefalomedular (PFN). Cirurgia em <48h reduz mortalidade. Ref: AAOS CPG Hip Fractures in Elderly. 2021.', 'https://www.aaos.org/quality/quality-programs/clinical-practice-guidelines/', 2021, 'fratura fêmur,colo femoral,artroplastia,Garden,transtrocantérica', 700, 0, NOW()),

-- EMERGÊNCIA
(UUID(), 'Parada Cardiorrespiratória (PCR) — ACLS 2020', 'American Heart Association (AHA)', 'Emergência', 'guideline', 'Algoritmo: C-A-B. RCP alta qualidade: 100-120/min, profundidade 5-6cm, retorno completo do tórax. Ritmos chocáveis: FV/TV sem pulso → desfibrilação + epinefrina 1mg a cada 3-5min + amiodarona 300mg. Não chocáveis: assistolia/AESP → epinefrina imediata + tratar causas reversíveis (5H/5T). Ref: Panchal AR et al. Circulation. 2020;142(16_suppl_2):S366-S468. PMID: 33081529', 'https://www.ahajournals.org/doi/10.1161/CIR.0000000000000916', 2020, 'PCR,ACLS,RCP,desfibrilação,epinefrina,amiodarona', 3000, 39.918, NOW()),

(UUID(), 'Anafilaxia — Diagnóstico e Tratamento de Emergência', 'World Allergy Organization (WAO)', 'Emergência', 'guideline', 'Diagnóstico: início agudo (minutos a horas) com envolvimento de pele/mucosa + respiratório ou cardiovascular. Tratamento: EPINEFRINA IM 0.3-0.5mg (0.01mg/kg em crianças) na face anterolateral da coxa — REPETIR a cada 5-15min. Posição: decúbito dorsal com MMII elevados. Ref: Cardona V et al. World Allergy Organ J. 2020;13(10):100472. PMID: 33204386', 'https://waojournal.biomedcentral.com/', 2020, 'anafilaxia,epinefrina,adrenalina,choque anafilático,alergia', 800, 5.016, NOW()),

-- ONCOLOGIA
(UUID(), 'Câncer de Mama — Rastreamento e Diagnóstico', 'Instituto Nacional de Câncer (INCA)', 'Oncologia', 'guideline', 'Rastreamento: mamografia bienal 50-69 anos (INCA) ou anual 40+ (SBM/CBR). Diagnóstico: mamografia BI-RADS + biópsia (core biopsy). Estadiamento TNM. Tratamento: cirurgia (conservadora ou mastectomia) + RT adjuvante + QT/HT conforme subtipo molecular (Luminal A/B, HER2+, triplo-negativo). Ref: INCA. Diretrizes para Detecção Precoce do Câncer de Mama. 2022.', 'https://www.inca.gov.br/', 2022, 'câncer de mama,mamografia,BI-RADS,mastectomia,quimioterapia', 1000, 0, NOW()),

-- UROLOGIA
(UUID(), 'Hiperplasia Prostática Benigna (HPB) — Diagnóstico e Tratamento', 'European Association of Urology (EAU)', 'Urologia', 'guideline', 'Diagnóstico: IPSS (leve 0-7, moderado 8-19, grave 20-35) + toque retal + PSA + USG. Tratamento: IPSS leve → vigilância ativa; moderado → alfa-bloqueador (tansulosina) ou inibidor 5α-redutase (finasterida); grave/refratário → RTU de próstata ou HoLEP. Ref: EAU Guidelines on BPH. 2024.', 'https://uroweb.org/guidelines/', 2024, 'HPB,próstata,IPSS,tansulosina,finasterida,RTU', 600, 0, NOW());
