export interface ComponenteDissecacao {
  nome: string;
  descricao: string;
}

export interface OrgaoData {
  id: string;
  nome: string;
  nomeLatim: string;
  imagem: string;
  sistema: string;
  descricao: string;
  funcao: string;
  localizacao: string;
  irrigacao: string;
  inervacao: string;
  patologias: string[];
  componentes: ComponenteDissecacao[];
  curiosidade: string;
}

export interface SistemaData {
  id: string;
  nome: string;
  icone: string;
  cor: string;
  descricao: string;
}

export const SISTEMAS: SistemaData[] = [
  { id: 'cardiovascular', nome: 'Cardiovascular', icone: '\u2764\uFE0F', cor: '#ef4444', descricao: 'Responsavel pela circulacao do sangue' },
  { id: 'respiratorio', nome: 'Respiratorio', icone: '\uD83E\uDEC1', cor: '#3b82f6', descricao: 'Trocas gasosas e ventilacao pulmonar' },
  { id: 'nervoso', nome: 'Nervoso', icone: '\uD83E\uDDE0', cor: '#a855f7', descricao: 'Controle e coordenacao do organismo' },
  { id: 'digestorio', nome: 'Digestorio', icone: '\uD83C\uDF56', cor: '#f59e0b', descricao: 'Digestao e absorcao de nutrientes' },
  { id: 'urinario', nome: 'Urinario', icone: '\uD83D\uDCA7', cor: '#06b6d4', descricao: 'Filtracao do sangue e excrecao' },
  { id: 'endocrino', nome: 'Endocrino', icone: '\uD83E\uDD8B', cor: '#ec4899', descricao: 'Regulacao hormonal do organismo' },
  { id: 'musculoesqueletico', nome: 'Musculoesqueletico', icone: '\uD83E\uDDB4', cor: '#f97316', descricao: 'Sustentacao, protecao e movimento' },
  { id: 'reprodutor', nome: 'Reprodutor', icone: '\uD83E\uDDEC', cor: '#14b8a6', descricao: 'Reproducao humana' },
  { id: 'sentidos', nome: 'Orgaos dos Sentidos', icone: '\uD83D\uDC41\uFE0F', cor: '#8b5cf6', descricao: 'Captacao de estimulos sensoriais' },
];

export const ORGAOS: OrgaoData[] = [
  // CARDIOVASCULAR
  {
    id: 'coracao', nome: 'Coracao', nomeLatim: 'Cor', imagem: '/atlas-organs/coracao.png', sistema: 'cardiovascular',
    descricao: 'Orgao muscular oco que bombeia sangue para todo o corpo. Possui 4 camaras: 2 atrios e 2 ventriculos.',
    funcao: 'Bombear sangue oxigenado para o corpo e sangue desoxigenado para os pulmoes.',
    localizacao: 'Mediastino medio, entre os pulmoes, posterior ao esterno.',
    irrigacao: 'Arterias coronarias direita e esquerda (ramos da aorta ascendente).',
    inervacao: 'Plexo cardiaco (simpatico e parassimpatico via nervo vago).',
    patologias: ['Infarto Agudo do Miocardio', 'Insuficiencia Cardiaca', 'Arritmias', 'Valvopatias', 'Endocardite'],
    componentes: [
      { nome: 'Epicardio', descricao: 'Camada serosa externa (pericardio visceral)' },
      { nome: 'Miocardio', descricao: 'Camada muscular responsavel pela contracao' },
      { nome: 'Endocardio', descricao: 'Revestimento interno das camaras' },
      { nome: 'Atrio Direito', descricao: 'Recebe sangue venoso das veias cavas' },
      { nome: 'Atrio Esquerdo', descricao: 'Recebe sangue oxigenado das veias pulmonares' },
      { nome: 'Ventriculo Direito', descricao: 'Bombeia sangue para a arteria pulmonar' },
      { nome: 'Ventriculo Esquerdo', descricao: 'Bombeia sangue para a aorta' },
      { nome: 'Valvula Tricuspide', descricao: 'Entre atrio e ventriculo direito' },
      { nome: 'Valvula Mitral', descricao: 'Entre atrio e ventriculo esquerdo' },
      { nome: 'Valvula Aortica', descricao: 'Na saida do ventriculo esquerdo' },
      { nome: 'Valvula Pulmonar', descricao: 'Na saida do ventriculo direito' },
      { nome: 'Septo Interventricular', descricao: 'Parede entre os ventriculos' },
      { nome: 'Arterias Coronarias', descricao: 'Vasos que irrigam o miocardio' },
    ],
    curiosidade: 'O coracao bate cerca de 100.000 vezes por dia, bombeando aproximadamente 7.500 litros de sangue.',
  },
  {
    id: 'aorta', nome: 'Aorta', nomeLatim: 'Aorta', imagem: '/atlas-organs/aorta.png', sistema: 'cardiovascular',
    descricao: 'Maior arteria do corpo humano, origina-se do ventriculo esquerdo e distribui sangue oxigenado.',
    funcao: 'Conduzir sangue oxigenado do coracao para todo o corpo.',
    localizacao: 'Origina-se no ventriculo esquerdo, percorre torax e abdomen.',
    irrigacao: 'Vasa vasorum (pequenos vasos na parede arterial).',
    inervacao: 'Plexo aortico (simpatico).',
    patologias: ['Aneurisma de Aorta', 'Disseccao Aortica', 'Coarctacao da Aorta', 'Aterosclerose'],
    componentes: [
      { nome: 'Aorta Ascendente', descricao: 'Parte inicial, origina as coronarias' },
      { nome: 'Arco Aortico', descricao: 'Curva superior com ramos para cabeca e MMSS' },
      { nome: 'Aorta Descendente', descricao: 'Percorre torax e abdomen' },
      { nome: 'Arterias Carotidas', descricao: 'Ramos do arco para o cerebro' },
      { nome: 'Arterias Subclavias', descricao: 'Ramos do arco para MMSS' },
    ],
    curiosidade: 'A aorta tem diametro de 2,5-3,5 cm e suporta pressoes de ate 120 mmHg.',
  },
  {
    id: 'veia-cava-superior', nome: 'Veia Cava Superior', nomeLatim: 'Vena cava superior', imagem: '/atlas-organs/veia-cava-superior.png', sistema: 'cardiovascular',
    descricao: 'Grande veia que drena sangue da cabeca, pescoco e membros superiores para o atrio direito.',
    funcao: 'Retornar sangue venoso da metade superior do corpo ao coracao.',
    localizacao: 'Mediastino superior, anterior a traqueia.',
    irrigacao: 'Vasa vasorum.',
    inervacao: 'Plexo simpatico.',
    patologias: ['Sindrome da Veia Cava Superior', 'Trombose'],
    componentes: [
      { nome: 'Tronco Principal', descricao: 'Veia cava superior propriamente dita' },
      { nome: 'Veias Braquiocefalicas', descricao: 'Formam a VCS por confluencia' },
    ],
    curiosidade: 'A sindrome da VCS pode ser causada por tumores mediastinais.',
  },
  {
    id: 'veia-cava-inferior', nome: 'Veia Cava Inferior', nomeLatim: 'Vena cava inferior', imagem: '/atlas-organs/veia-cava-inferior.png', sistema: 'cardiovascular',
    descricao: 'Maior veia do corpo, drena sangue da metade inferior do corpo para o atrio direito.',
    funcao: 'Retornar sangue venoso da metade inferior do corpo ao coracao.',
    localizacao: 'Retroperitoneal, a direita da aorta abdominal.',
    irrigacao: 'Vasa vasorum.',
    inervacao: 'Plexo simpatico.',
    patologias: ['Trombose da VCI', 'Sindrome de Budd-Chiari'],
    componentes: [
      { nome: 'Tronco Principal', descricao: 'VCI propriamente dita' },
      { nome: 'Veias Iliacas Comuns', descricao: 'Formam a VCI por confluencia' },
    ],
    curiosidade: 'A VCI nao possui valvulas em grande parte de seu trajeto.',
  },
  {
    id: 'arterias-coronarias', nome: 'Arterias Coronarias', nomeLatim: 'Arteriae coronariae', imagem: '/atlas-organs/arterias-coronarias.png', sistema: 'cardiovascular',
    descricao: 'Vasos que irrigam o miocardio, originam-se dos seios aorticos.',
    funcao: 'Fornecer sangue oxigenado ao musculo cardiaco.',
    localizacao: 'Superficie do coracao, nos sulcos coronarios.',
    irrigacao: 'Auto-irrigacao do miocardio.',
    inervacao: 'Plexo cardiaco.',
    patologias: ['Doenca Arterial Coronariana', 'Angina', 'Infarto do Miocardio'],
    componentes: [
      { nome: 'Coronaria Direita', descricao: 'Irriga VD e parede inferior do VE' },
      { nome: 'Coronaria Esquerda', descricao: 'Tronco que se divide em DA e Cx' },
      { nome: 'Descendente Anterior', descricao: 'Irriga parede anterior do VE e septo' },
      { nome: 'Circunflexa', descricao: 'Irriga parede lateral do VE' },
    ],
    curiosidade: 'A obstrucao da DA e conhecida como "arteria da viuva" por sua alta mortalidade.',
  },
  // RESPIRATORIO
  {
    id: 'pulmoes', nome: 'Pulmoes', nomeLatim: 'Pulmones', imagem: '/atlas-organs/pulmoes.png', sistema: 'respiratorio',
    descricao: 'Orgaos esponjosos responsaveis pelas trocas gasosas. Direito: 3 lobos. Esquerdo: 2 lobos.',
    funcao: 'Realizar trocas gasosas (O2 e CO2) nos alveolos pulmonares.',
    localizacao: 'Cavidade toracica, lateralmente ao mediastino.',
    irrigacao: 'Arterias pulmonares (funcional) e bronquicas (nutritiva).',
    inervacao: 'Plexo pulmonar (simpatico e parassimpatico via nervo vago).',
    patologias: ['Pneumonia', 'DPOC', 'Asma', 'Embolia Pulmonar', 'Cancer de Pulmao'],
    componentes: [
      { nome: 'Pulmao Direito', descricao: '3 lobos (superior, medio, inferior)' },
      { nome: 'Pulmao Esquerdo', descricao: '2 lobos (superior, inferior)' },
      { nome: 'Bronquios Principais', descricao: 'Entradas dos pulmoes' },
      { nome: 'Bronquios Lobares', descricao: 'Ramificacoes para cada lobo' },
      { nome: 'Alveolos', descricao: 'Unidades funcionais de troca gasosa' },
    ],
    curiosidade: 'Os pulmoes possuem cerca de 300 milhoes de alveolos com area total de ~70m2.',
  },
  {
    id: 'traqueia', nome: 'Traqueia', nomeLatim: 'Trachea', imagem: '/atlas-organs/traqueia.png', sistema: 'respiratorio',
    descricao: 'Tubo cartilaginoso que conduz ar da laringe aos bronquios.',
    funcao: 'Conduzir ar entre a laringe e os bronquios, filtrar e aquecer o ar.',
    localizacao: 'Regiao cervical anterior, da laringe ate a carina (T4-T5).',
    irrigacao: 'Arterias tireoideas inferiores.',
    inervacao: 'Nervo laringeo recorrente e nervo vago.',
    patologias: ['Traqueite', 'Estenose Traqueal', 'Traqueomalacia'],
    componentes: [
      { nome: 'Aneis Traqueais', descricao: '16-20 aneis cartilaginosos em C' },
      { nome: 'Musculo Traqueal', descricao: 'Parede posterior membranosa' },
      { nome: 'Carina', descricao: 'Bifurcacao em bronquios principais' },
    ],
    curiosidade: 'A traqueia tem cerca de 10-12 cm de comprimento e 2,5 cm de diametro.',
  },
  {
    id: 'laringe', nome: 'Laringe', nomeLatim: 'Larynx', imagem: '/atlas-organs/laringe.png', sistema: 'respiratorio',
    descricao: 'Orgao da fonacao que conecta a faringe a traqueia.',
    funcao: 'Producao de voz, protecao das vias aereas durante a degluticao.',
    localizacao: 'Regiao cervical anterior, nivel C3-C6.',
    irrigacao: 'Arterias laringeas superior e inferior.',
    inervacao: 'Nervos laringeos superior e recorrente (ramos do vago).',
    patologias: ['Laringite', 'Nodulos Vocais', 'Cancer de Laringe', 'Paralisia de Cordas Vocais'],
    componentes: [
      { nome: 'Cartilagem Tireoide', descricao: 'Pomo de Adao, maior cartilagem' },
      { nome: 'Cartilagem Cricoide', descricao: 'Anel inferior completo' },
      { nome: 'Epiglote', descricao: 'Aba que protege a via aerea' },
      { nome: 'Cordas Vocais', descricao: 'Pregas vocais verdadeiras' },
    ],
    curiosidade: 'As cordas vocais vibram entre 100-300 Hz durante a fonacao.',
  },
  {
    id: 'diafragma', nome: 'Diafragma', nomeLatim: 'Diaphragma', imagem: '/atlas-organs/diafragma.png', sistema: 'respiratorio',
    descricao: 'Principal musculo da respiracao, separa torax do abdomen.',
    funcao: 'Contracao para inspiracao, relaxamento para expiracao.',
    localizacao: 'Limite entre cavidades toracica e abdominal.',
    irrigacao: 'Arterias frenicas superior e inferior.',
    inervacao: 'Nervo frenico (C3-C5).',
    patologias: ['Hernia Diafragmatica', 'Paralisia Diafragmatica', 'Hernia de Hiato'],
    componentes: [
      { nome: 'Cupula Direita', descricao: 'Mais elevada (figado abaixo)' },
      { nome: 'Cupula Esquerda', descricao: 'Ligeiramente mais baixa' },
      { nome: 'Hiato Esofagico', descricao: 'Passagem do esofago' },
      { nome: 'Hiato Aortico', descricao: 'Passagem da aorta' },
    ],
    curiosidade: 'O soluço e uma contracao involuntaria e espamodica do diafragma.',
  },
  // NERVOSO
  {
    id: 'cerebro', nome: 'Cerebro', nomeLatim: 'Cerebrum', imagem: '/atlas-organs/cerebro.png', sistema: 'nervoso',
    descricao: 'Centro de controle do sistema nervoso com funcoes cognitivas, sensoriais e motoras.',
    funcao: 'Processamento sensorial, controle motor, funcoes cognitivas superiores.',
    localizacao: 'Cavidade craniana, protegido pelas meninges.',
    irrigacao: 'Arterias carotidas internas e vertebrais (Poligono de Willis).',
    inervacao: 'Nervos cranianos (I-XII).',
    patologias: ['AVC', 'Tumores Cerebrais', 'Epilepsia', 'Alzheimer', 'Parkinson'],
    componentes: [
      { nome: 'Lobo Frontal', descricao: 'Funcoes executivas, personalidade, area motora' },
      { nome: 'Lobo Parietal', descricao: 'Sensibilidade, orientacao espacial' },
      { nome: 'Lobo Temporal', descricao: 'Audicao, memoria, linguagem' },
      { nome: 'Lobo Occipital', descricao: 'Processamento visual' },
      { nome: 'Corpo Caloso', descricao: 'Conexao entre hemisferios' },
      { nome: 'Talamo', descricao: 'Centro de retransmissao sensorial' },
      { nome: 'Hipotalamo', descricao: 'Controle de funcoes vitais e hormonais' },
      { nome: 'Ganglios da Base', descricao: 'Controle motor extrapiramidal' },
    ],
    curiosidade: 'O cerebro consome 20% do oxigenio corporal apesar de representar apenas 2% do peso.',
  },
  {
    id: 'cerebelo', nome: 'Cerebelo', nomeLatim: 'Cerebellum', imagem: '/atlas-organs/cerebelo.png', sistema: 'nervoso',
    descricao: 'Estrutura posterior do encefalo responsavel pela coordenacao motora e equilibrio.',
    funcao: 'Coordenacao de movimentos, equilibrio, tono muscular.',
    localizacao: 'Fossa craniana posterior, abaixo do cerebro.',
    irrigacao: 'Arterias cerebelares (superior, inferior anterior e posterior).',
    inervacao: 'Pedunculos cerebelares (superior, medio, inferior).',
    patologias: ['Ataxia Cerebelar', 'Tumores do Cerebelo', 'Sindrome Vertiginosa'],
    componentes: [
      { nome: 'Hemisferios Cerebelares', descricao: 'Partes laterais, coordenacao fina' },
      { nome: 'Verme Cerebelar', descricao: 'Parte central, equilibrio e postura' },
    ],
    curiosidade: 'O cerebelo contem mais de 50% dos neuronios do encefalo.',
  },
  {
    id: 'tronco-encefalico', nome: 'Tronco Encefalico', nomeLatim: 'Truncus encephalicus', imagem: '/atlas-organs/tronco-encefalico.png', sistema: 'nervoso',
    descricao: 'Estrutura que conecta o cerebro a medula espinhal, controla funcoes vitais.',
    funcao: 'Controle de funcoes vitais (respiracao, FC, PA), passagem de vias nervosas.',
    localizacao: 'Base do encefalo, anterior ao cerebelo.',
    irrigacao: 'Arteria basilar e ramos.',
    inervacao: 'Origem dos nervos cranianos III-XII.',
    patologias: ['AVC de Tronco', 'Tumores do Tronco', 'Morte Encefalica'],
    componentes: [
      { nome: 'Mesencefalo', descricao: 'Parte superior, reflexos visuais e auditivos' },
      { nome: 'Ponte', descricao: 'Parte media, conexao cerebro-cerebelo' },
      { nome: 'Bulbo (Medula Oblonga)', descricao: 'Parte inferior, centros vitais' },
    ],
    curiosidade: 'A morte encefalica e definida pela ausencia de funcao do tronco encefalico.',
  },
  {
    id: 'medula-espinhal', nome: 'Medula Espinhal', nomeLatim: 'Medulla spinalis', imagem: '/atlas-organs/medula-espinhal.png', sistema: 'nervoso',
    descricao: 'Estrutura nervosa cilindrica dentro do canal vertebral que transmite impulsos nervosos.',
    funcao: 'Conducao de impulsos nervosos, arcos reflexos.',
    localizacao: 'Canal vertebral, de C1 ate L1-L2 (cone medular).',
    irrigacao: 'Arteria espinhal anterior e posteriores.',
    inervacao: '31 pares de nervos espinhais.',
    patologias: ['Lesao Medular', 'Mielite Transversa', 'Siringomielia'],
    componentes: [
      { nome: 'Substancia Cinzenta', descricao: 'Forma de H, corpos neuronais' },
      { nome: 'Substancia Branca', descricao: 'Tratos ascendentes e descendentes' },
      { nome: 'Nervos Espinhais', descricao: '31 pares (8C, 12T, 5L, 5S, 1Co)' },
    ],
    curiosidade: 'A medula espinhal tem apenas 45 cm de comprimento e 1 cm de diametro.',
  },
  {
    id: 'nervo-optico', nome: 'Nervo Optico', nomeLatim: 'Nervus opticus', imagem: '/atlas-organs/nervo-optico.png', sistema: 'nervoso',
    descricao: 'II par craniano que transmite informacoes visuais da retina ao cerebro.',
    funcao: 'Transmitir impulsos visuais da retina ao cortex visual occipital.',
    localizacao: 'Da retina ao quiasma optico, passando pelo canal optico.',
    irrigacao: 'Arteria oftalmica.',
    inervacao: 'Fibras aferentes visuais.',
    patologias: ['Neurite Optica', 'Papiledema', 'Atrofia Optica', 'Glaucoma'],
    componentes: [
      { nome: 'Nervo Optico', descricao: 'Trajeto do olho ao quiasma' },
      { nome: 'Quiasma Optico', descricao: 'Cruzamento parcial das fibras' },
    ],
    curiosidade: 'O nervo optico contem cerca de 1,2 milhao de fibras nervosas.',
  },
  // DIGESTORIO
  {
    id: 'estomago', nome: 'Estomago', nomeLatim: 'Gaster', imagem: '/atlas-organs/estomago.png', sistema: 'digestorio',
    descricao: 'Orgao muscular oco em forma de J que armazena e digere alimentos.',
    funcao: 'Armazenamento, digestao mecanica e quimica dos alimentos.',
    localizacao: 'Epigastrio e hipocondrio esquerdo.',
    irrigacao: 'Arterias gastricas e gastroepiploicas.',
    inervacao: 'Nervo vago e plexo celiaco.',
    patologias: ['Gastrite', 'Ulcera Peptica', 'Cancer Gastrico', 'DRGE'],
    componentes: [
      { nome: 'Cardia', descricao: 'Juncao esofago-gastrica' },
      { nome: 'Fundo', descricao: 'Parte superior, reservatorio de gas' },
      { nome: 'Corpo', descricao: 'Parte principal, secrecao acida' },
      { nome: 'Antro', descricao: 'Parte inferior, producao de gastrina' },
      { nome: 'Piloro', descricao: 'Esfincter de saida para o duodeno' },
    ],
    curiosidade: 'O estomago produz cerca de 2-3 litros de suco gastrico por dia.',
  },
  {
    id: 'intestino-delgado', nome: 'Intestino Delgado', nomeLatim: 'Intestinum tenue', imagem: '/atlas-organs/intestino-delgado.png', sistema: 'digestorio',
    descricao: 'Porcao do TGI onde ocorre a maior parte da digestao e absorcao de nutrientes.',
    funcao: 'Digestao final e absorcao de nutrientes, agua e eletrolitos.',
    localizacao: 'Cavidade abdominal, entre estomago e ceco.',
    irrigacao: 'Arteria mesenterica superior.',
    inervacao: 'Plexo mesenterica e nervo vago.',
    patologias: ['Doenca de Crohn', 'Doenca Celiaca', 'Obstrucao Intestinal'],
    componentes: [
      { nome: 'Duodeno', descricao: '25-30 cm, recebe bile e suco pancreatico' },
      { nome: 'Jejuno', descricao: '~2,5 m, principal local de absorcao' },
      { nome: 'Ileo', descricao: '~3,5 m, absorve B12 e sais biliares' },
    ],
    curiosidade: 'O intestino delgado tem area de absorcao de ~200 m2 gracas as vilosidades.',
  },
  {
    id: 'intestino-grosso', nome: 'Intestino Grosso', nomeLatim: 'Intestinum crassum', imagem: '/atlas-organs/intestino-grosso.png', sistema: 'digestorio',
    descricao: 'Porcao final do TGI responsavel pela absorcao de agua e formacao das fezes.',
    funcao: 'Absorcao de agua e eletrolitos, formacao e armazenamento de fezes.',
    localizacao: 'Cavidade abdominal, emoldurando o intestino delgado.',
    irrigacao: 'Arterias mesentericas superior e inferior.',
    inervacao: 'Plexo mesenterica, nervos esplancnicos.',
    patologias: ['Retocolite Ulcerativa', 'Cancer Colorretal', 'Diverticulite', 'Polipos'],
    componentes: [
      { nome: 'Ceco e Apendice', descricao: 'Inicio do colon, apendice vermiforme' },
      { nome: 'Colon Ascendente', descricao: 'Lado direito do abdomen' },
      { nome: 'Colon Transverso', descricao: 'Cruza o abdomen horizontalmente' },
      { nome: 'Colon Descendente', descricao: 'Lado esquerdo do abdomen' },
      { nome: 'Sigmoide', descricao: 'Porcao em S antes do reto' },
      { nome: 'Reto', descricao: 'Porcao final, armazena fezes' },
    ],
    curiosidade: 'O intestino grosso abriga trilhoes de bacterias que formam a microbiota intestinal.',
  },
  {
    id: 'figado', nome: 'Figado', nomeLatim: 'Hepar', imagem: '/atlas-organs/figado.png', sistema: 'digestorio',
    descricao: 'Maior glandula do corpo, essencial para metabolismo, detoxificacao e producao de bile.',
    funcao: 'Metabolismo, producao de bile, detoxificacao, sintese de proteinas plasmaticas.',
    localizacao: 'Hipocondrio direito e epigastrio.',
    irrigacao: 'Arteria hepatica propria (30%) e veia porta (70%).',
    inervacao: 'Plexo hepatico.',
    patologias: ['Hepatite', 'Cirrose', 'Esteatose', 'Carcinoma Hepatocelular'],
    componentes: [
      { nome: 'Lobo Direito', descricao: 'Maior lobo do figado' },
      { nome: 'Lobo Esquerdo', descricao: 'Menor, a esquerda do ligamento falciforme' },
      { nome: 'Lobo Caudado', descricao: 'Posterior, entre VCI e ligamento venoso' },
      { nome: 'Lobo Quadrado', descricao: 'Inferior, entre vesicula e lig. redondo' },
      { nome: 'Veia Porta', descricao: 'Traz sangue do TGI para metabolismo' },
      { nome: 'Veias Hepaticas', descricao: 'Drenam para a VCI' },
    ],
    curiosidade: 'O figado tem capacidade regenerativa: pode se recuperar com apenas 25% do tecido original.',
  },
  {
    id: 'pancreas', nome: 'Pancreas', nomeLatim: 'Pancreas', imagem: '/atlas-organs/pancreas.png', sistema: 'digestorio',
    descricao: 'Glandula mista (exocrina e endocrina) que produz enzimas digestivas e hormonios.',
    funcao: 'Producao de insulina, glucagon (endocrina) e enzimas digestivas (exocrina).',
    localizacao: 'Retroperitoneal, posterior ao estomago.',
    irrigacao: 'Arterias pancreaticoduodenais e esplenica.',
    inervacao: 'Plexo celiaco e nervo vago.',
    patologias: ['Diabetes Mellitus', 'Pancreatite', 'Cancer de Pancreas'],
    componentes: [
      { nome: 'Cabeca', descricao: 'Encaixada na curvatura do duodeno' },
      { nome: 'Corpo', descricao: 'Parte central do pancreas' },
      { nome: 'Cauda', descricao: 'Extremidade que toca o baco' },
      { nome: 'Ducto Pancreatico', descricao: 'Drena secrecoes para o duodeno' },
      { nome: 'Ilhotas de Langerhans', descricao: 'Celulas endocrinas (alfa, beta, delta)' },
    ],
    curiosidade: 'As ilhotas de Langerhans representam apenas 1-2% da massa pancreatica.',
  },
  {
    id: 'vesicula-biliar', nome: 'Vesicula Biliar', nomeLatim: 'Vesica biliaris', imagem: '/atlas-organs/vesicula-biliar.png', sistema: 'digestorio',
    descricao: 'Orgao piriforme que armazena e concentra a bile produzida pelo figado.',
    funcao: 'Armazenar, concentrar e liberar bile para digestao de gorduras.',
    localizacao: 'Fossa da vesicula biliar, face visceral do figado.',
    irrigacao: 'Arteria cistica (ramo da hepatica direita).',
    inervacao: 'Plexo celiaco e nervo vago.',
    patologias: ['Colelitiase', 'Colecistite', 'Coledocolitiase'],
    componentes: [
      { nome: 'Fundo', descricao: 'Extremidade arredondada' },
      { nome: 'Corpo', descricao: 'Parte principal' },
      { nome: 'Colo', descricao: 'Parte estreita que continua como ducto cistico' },
      { nome: 'Ducto Cistico', descricao: 'Conecta ao ducto coledoco' },
    ],
    curiosidade: 'A vesicula biliar armazena 30-50 mL de bile concentrada.',
  },
  // URINARIO
  {
    id: 'rins', nome: 'Rins', nomeLatim: 'Renes', imagem: '/atlas-organs/rins.png', sistema: 'urinario',
    descricao: 'Orgaos pares em forma de feijao responsaveis pela filtracao do sangue.',
    funcao: 'Filtracao glomerular, regulacao hidroeletrolitica, producao de eritropoietina.',
    localizacao: 'Retroperitoneal, entre T12-L3.',
    irrigacao: 'Arterias renais (ramos da aorta abdominal).',
    inervacao: 'Plexo renal (simpatico T10-L1).',
    patologias: ['Insuficiencia Renal', 'Glomerulonefrite', 'Nefrolitiase', 'Pielonefrite'],
    componentes: [
      { nome: 'Cortex Renal', descricao: 'Camada externa com glomerulos' },
      { nome: 'Medula Renal', descricao: 'Piramides renais com tubulos' },
      { nome: 'Pelve Renal', descricao: 'Coleta urina dos calices' },
      { nome: 'Nefron', descricao: 'Unidade funcional (glomerulo + tubulos)' },
      { nome: 'Calices Renais', descricao: 'Coletam urina das piramides' },
    ],
    curiosidade: 'Os rins filtram cerca de 180 litros de sangue por dia, produzindo 1-2L de urina.',
  },
  {
    id: 'bexiga-urinaria', nome: 'Bexiga Urinaria', nomeLatim: 'Vesica urinaria', imagem: '/atlas-organs/bexiga-urinaria.png', sistema: 'urinario',
    descricao: 'Orgao muscular oco que armazena urina ate a miccao.',
    funcao: 'Armazenamento de urina e contracao para miccao.',
    localizacao: 'Pelve, posterior a sinfise pubica.',
    irrigacao: 'Arterias vesicais superior e inferior.',
    inervacao: 'Plexo vesical (parassimpatico S2-S4).',
    patologias: ['Cistite', 'Incontinencia Urinaria', 'Cancer de Bexiga'],
    componentes: [
      { nome: 'Musculo Detrusor', descricao: 'Musculo liso da parede vesical' },
      { nome: 'Trigono Vesical', descricao: 'Area entre ostios ureterais e uretra' },
      { nome: 'Esfincter Interno', descricao: 'Controle involuntario' },
      { nome: 'Esfincter Externo', descricao: 'Controle voluntario' },
    ],
    curiosidade: 'A bexiga pode armazenar ate 500 mL, mas a vontade de urinar surge com 200-300 mL.',
  },
  {
    id: 'ureteres', nome: 'Ureteres', nomeLatim: 'Ureteres', imagem: '/atlas-organs/ureteres.png', sistema: 'urinario',
    descricao: 'Tubos musculares que conduzem urina dos rins a bexiga por peristaltismo.',
    funcao: 'Transportar urina dos rins ate a bexiga urinaria.',
    localizacao: 'Retroperitoneal, da pelve renal ate a bexiga.',
    irrigacao: 'Arterias renais, gonadais e vesicais.',
    inervacao: 'Plexo renal e hipogastrico.',
    patologias: ['Calculo Ureteral', 'Estenose Ureteral', 'Refluxo Vesicoureteral'],
    componentes: [
      { nome: 'Porcao Abdominal', descricao: 'Trajeto retroperitoneal' },
      { nome: 'Porcao Pelvica', descricao: 'Cruza vasos iliacos' },
      { nome: 'Porcao Intramural', descricao: 'Atravessa parede da bexiga' },
    ],
    curiosidade: 'Cada ureter tem cerca de 25-30 cm e 3-4 mm de diametro.',
  },
  // ENDOCRINO
  {
    id: 'tireoide', nome: 'Tireoide', nomeLatim: 'Glandula thyroidea', imagem: '/atlas-organs/tireoide.png', sistema: 'endocrino',
    descricao: 'Glandula endocrina em forma de borboleta que regula o metabolismo.',
    funcao: 'Producao de T3, T4 e calcitonina para regulacao metabolica.',
    localizacao: 'Regiao cervical anterior, abaixo da cartilagem tireoide.',
    irrigacao: 'Arterias tireoideas superior e inferior.',
    inervacao: 'Nervos laringeos recorrentes e superiores.',
    patologias: ['Hipotireoidismo', 'Hipertireoidismo', 'Bocio', 'Cancer de Tireoide'],
    componentes: [
      { nome: 'Lobo Direito', descricao: 'Lobo lateral direito' },
      { nome: 'Lobo Esquerdo', descricao: 'Lobo lateral esquerdo' },
      { nome: 'Istmo', descricao: 'Conexao entre os lobos' },
      { nome: 'Foliculos Tireoidianos', descricao: 'Unidades funcionais com coloide' },
      { nome: 'Celulas Parafoliculares', descricao: 'Produzem calcitonina' },
    ],
    curiosidade: 'A tireoide e a maior glandula endocrina do corpo humano.',
  },
  {
    id: 'glandulas-adrenais', nome: 'Glandulas Adrenais', nomeLatim: 'Glandulae suprarenales', imagem: '/atlas-organs/glandulas-adrenais.png', sistema: 'endocrino',
    descricao: 'Glandulas endocrinas situadas sobre os rins que produzem hormonios vitais.',
    funcao: 'Producao de cortisol, aldosterona, adrenalina e noradrenalina.',
    localizacao: 'Polo superior de cada rim, retroperitoneal.',
    irrigacao: 'Arterias suprarrenais (superior, media, inferior).',
    inervacao: 'Nervos esplancnicos (simpatico).',
    patologias: ['Sindrome de Cushing', 'Doenca de Addison', 'Feocromocitoma', 'Hiperaldosteronismo'],
    componentes: [
      { nome: 'Cortex Adrenal', descricao: 'Zona glomerulosa, fasciculada e reticular' },
      { nome: 'Medula Adrenal', descricao: 'Produz catecolaminas (adrenalina)' },
      { nome: 'Zona Glomerulosa', descricao: 'Produz aldosterona' },
      { nome: 'Zona Fasciculada', descricao: 'Produz cortisol' },
      { nome: 'Zona Reticular', descricao: 'Produz androgenios' },
    ],
    curiosidade: 'A medula adrenal e derivada da crista neural (tecido nervoso).',
  },
  {
    id: 'hipofise', nome: 'Hipofise', nomeLatim: 'Hypophysis', imagem: '/atlas-organs/hipofise.png', sistema: 'endocrino',
    descricao: 'Glandula mestra do sistema endocrino, controla outras glandulas.',
    funcao: 'Producao de GH, TSH, ACTH, FSH, LH, prolactina, ADH, ocitocina.',
    localizacao: 'Sela turcica do osso esfenoide, base do cerebro.',
    irrigacao: 'Arterias hipofisarias superior e inferior.',
    inervacao: 'Eixo hipotalamo-hipofisario.',
    patologias: ['Adenoma Hipofisario', 'Hipopituitarismo', 'Diabetes Insipidus', 'Acromegalia'],
    componentes: [
      { nome: 'Adeno-hipofise', descricao: 'Lobo anterior, produz 6 hormonios' },
      { nome: 'Neuro-hipofise', descricao: 'Lobo posterior, libera ADH e ocitocina' },
      { nome: 'Haste Hipofisaria', descricao: 'Conexao com o hipotalamo' },
    ],
    curiosidade: 'A hipofise tem o tamanho de uma ervilha (1 cm) mas controla todo o sistema endocrino.',
  },
  // MUSCULOESQUELETICO
  {
    id: 'cranio', nome: 'Cranio', nomeLatim: 'Cranium', imagem: '/atlas-organs/cranio.png', sistema: 'musculoesqueletico',
    descricao: 'Estrutura ossea que protege o encefalo e abriga orgaos dos sentidos.',
    funcao: 'Protecao do encefalo, suporte para face e orgaos sensoriais.',
    localizacao: 'Extremidade superior do esqueleto axial.',
    irrigacao: 'Arterias meningeas (media e anterior).',
    inervacao: 'Nervos cranianos e ramos do trigemeo.',
    patologias: ['Fraturas Cranianas', 'Hematoma Epidural', 'Hematoma Subdural'],
    componentes: [
      { nome: 'Frontal', descricao: 'Osso da testa' },
      { nome: 'Parietais', descricao: 'Ossos laterais superiores (par)' },
      { nome: 'Temporais', descricao: 'Ossos laterais (par), abrigam orelha media' },
      { nome: 'Occipital', descricao: 'Osso posterior, forame magno' },
      { nome: 'Esfenoide', descricao: 'Osso central da base, sela turcica' },
      { nome: 'Etmoide', descricao: 'Osso da base anterior, lamina crivosa' },
    ],
    curiosidade: 'O cranio e formado por 22 ossos, sendo 8 do neurocranio e 14 do viscerocranio.',
  },
  {
    id: 'coluna-vertebral', nome: 'Coluna Vertebral', nomeLatim: 'Columna vertebralis', imagem: '/atlas-organs/coluna-vertebral.png', sistema: 'musculoesqueletico',
    descricao: 'Eixo osseo do corpo composto por 33 vertebras articuladas.',
    funcao: 'Sustentacao, protecao da medula espinhal, movimento do tronco.',
    localizacao: 'Regiao posterior do tronco, do cranio ao coccix.',
    irrigacao: 'Arterias vertebrais e segmentares.',
    inervacao: '31 pares de nervos espinhais.',
    patologias: ['Hernia de Disco', 'Espondilose', 'Escoliose', 'Estenose Espinhal'],
    componentes: [
      { nome: 'Cervical (C1-C7)', descricao: '7 vertebras, suportam a cabeca' },
      { nome: 'Toracica (T1-T12)', descricao: '12 vertebras, articulam com costelas' },
      { nome: 'Lombar (L1-L5)', descricao: '5 vertebras, suportam maior carga' },
      { nome: 'Sacro (S1-S5)', descricao: '5 vertebras fundidas' },
      { nome: 'Coccix', descricao: '4 vertebras fundidas (vestigial)' },
      { nome: 'Discos Intervertebrais', descricao: 'Amortecedores entre vertebras' },
    ],
    curiosidade: 'A coluna vertebral tem 4 curvaturas que funcionam como molas de amortecimento.',
  },
  {
    id: 'femur', nome: 'Femur', nomeLatim: 'Femur', imagem: '/atlas-organs/femur.png', sistema: 'musculoesqueletico',
    descricao: 'Maior e mais forte osso do corpo humano, localizado na coxa.',
    funcao: 'Sustentacao do peso corporal, locomocao, insercao muscular.',
    localizacao: 'Coxa, entre quadril e joelho.',
    irrigacao: 'Arteria femoral e circunflexas.',
    inervacao: 'Nervo femoral e obturatorio.',
    patologias: ['Fratura de Femur', 'Necrose Avascular da Cabeca', 'Osteoporose'],
    componentes: [
      { nome: 'Cabeca do Femur', descricao: 'Articula com o acetabulo' },
      { nome: 'Colo do Femur', descricao: 'Regiao vulneravel a fraturas' },
      { nome: 'Trocanteres', descricao: 'Maior e menor, insercoes musculares' },
      { nome: 'Diafise', descricao: 'Corpo do osso' },
      { nome: 'Condilos', descricao: 'Articulam com a tibia (joelho)' },
    ],
    curiosidade: 'O femur pode suportar ate 30 vezes o peso corporal durante atividades de impacto.',
  },
  {
    id: 'musculo-biceps', nome: 'Musculo Biceps Braquial', nomeLatim: 'Musculus biceps brachii', imagem: '/atlas-organs/musculo-biceps.png', sistema: 'musculoesqueletico',
    descricao: 'Musculo do braco com duas cabecas, principal flexor do cotovelo.',
    funcao: 'Flexao do cotovelo, supinacao do antebraco.',
    localizacao: 'Compartimento anterior do braco.',
    irrigacao: 'Arteria braquial.',
    inervacao: 'Nervo musculocutaneo (C5-C6).',
    patologias: ['Tendinite Bicipital', 'Ruptura do Tendao', 'Sindrome de Popeye'],
    componentes: [
      { nome: 'Cabeca Longa', descricao: 'Origem no tuberculo supraglenoidal' },
      { nome: 'Cabeca Curta', descricao: 'Origem no processo coracoide' },
      { nome: 'Ventre Muscular', descricao: 'Corpo do musculo' },
      { nome: 'Tendao Distal', descricao: 'Insercao na tuberosidade do radio' },
    ],
    curiosidade: 'O biceps e um dos musculos mais conhecidos, mas nao e o principal flexor do cotovelo (e o braquial).',
  },
  // REPRODUTOR
  {
    id: 'utero-ovarios', nome: 'Utero e Ovarios', nomeLatim: 'Uterus et Ovaria', imagem: '/atlas-organs/utero-ovarios.png', sistema: 'reprodutor',
    descricao: 'Orgaos do sistema reprodutor feminino responsaveis pela gestacao e producao de ovulos.',
    funcao: 'Gestacao (utero), producao de ovulos e hormonios (ovarios).',
    localizacao: 'Pelve feminina, entre bexiga e reto.',
    irrigacao: 'Arterias uterinas e ovaricas.',
    inervacao: 'Plexo hipogastrico inferior.',
    patologias: ['Mioma Uterino', 'Endometriose', 'Cancer de Ovario', 'Sindrome dos Ovarios Policisticos'],
    componentes: [
      { nome: 'Corpo do Utero', descricao: 'Parte principal, abriga o feto' },
      { nome: 'Colo do Utero', descricao: 'Parte inferior, canal cervical' },
      { nome: 'Endometrio', descricao: 'Revestimento interno, descama na menstruacao' },
      { nome: 'Miometrio', descricao: 'Camada muscular, contracoes no parto' },
      { nome: 'Ovarios', descricao: 'Producao de ovulos e hormonios (E2, P4)' },
      { nome: 'Tubas Uterinas', descricao: 'Captam ovulo e local de fecundacao' },
    ],
    curiosidade: 'O utero pode expandir de 7 cm para 35 cm durante a gestacao.',
  },
  {
    id: 'testiculos-prostata', nome: 'Testiculos e Prostata', nomeLatim: 'Testes et Prostata', imagem: '/atlas-organs/testiculos-prostata.png', sistema: 'reprodutor',
    descricao: 'Orgaos do sistema reprodutor masculino para producao de espermatozoides e hormonios.',
    funcao: 'Producao de espermatozoides e testosterona (testiculos), secrecao prostática (prostata).',
    localizacao: 'Testiculos: bolsa escrotal. Prostata: abaixo da bexiga.',
    irrigacao: 'Arterias testiculares e vesicais inferiores.',
    inervacao: 'Plexo testicular e hipogastrico.',
    patologias: ['Cancer de Prostata', 'Hiperplasia Prostatica', 'Cancer de Testiculo', 'Varicocele'],
    componentes: [
      { nome: 'Testiculos', descricao: 'Producao de espermatozoides e testosterona' },
      { nome: 'Epididimo', descricao: 'Maturacao e armazenamento de espermatozoides' },
      { nome: 'Prostata', descricao: 'Secrecao do liquido prostatico' },
      { nome: 'Vesiculas Seminais', descricao: 'Producao de liquido seminal' },
      { nome: 'Ducto Deferente', descricao: 'Transporte de espermatozoides' },
    ],
    curiosidade: 'A prostata produz cerca de 30% do volume do liquido seminal.',
  },
  // SENTIDOS
  {
    id: 'olho-humano', nome: 'Olho Humano', nomeLatim: 'Oculus humanus', imagem: '/atlas-organs/olho-humano.png', sistema: 'sentidos',
    descricao: 'Orgao sensorial da visao com sistema optico complexo.',
    funcao: 'Captacao de luz, formacao de imagens, percepcao visual.',
    localizacao: 'Orbita craniana.',
    irrigacao: 'Arteria oftalmica.',
    inervacao: 'Nervo optico (II), oculomotor (III), troclear (IV), abducente (VI).',
    patologias: ['Glaucoma', 'Catarata', 'Degeneracao Macular', 'Retinopatia Diabetica'],
    componentes: [
      { nome: 'Cornea', descricao: 'Camada transparente anterior, refracao' },
      { nome: 'Iris', descricao: 'Controla a entrada de luz (pupila)' },
      { nome: 'Cristalino', descricao: 'Lente biconvexa, acomodacao visual' },
      { nome: 'Retina', descricao: 'Camada sensorial com fotorreceptores' },
      { nome: 'Nervo Optico', descricao: 'Transmite impulsos ao cerebro' },
      { nome: 'Humor Vitreo', descricao: 'Gel transparente da camara posterior' },
    ],
    curiosidade: 'O olho humano pode distinguir cerca de 10 milhoes de cores diferentes.',
  },
  {
    id: 'orelha-humana', nome: 'Orelha Humana', nomeLatim: 'Auris humana', imagem: '/atlas-organs/orelha-humana.png', sistema: 'sentidos',
    descricao: 'Orgao da audicao e equilibrio com tres porcoes: externa, media e interna.',
    funcao: 'Audicao (captacao e transmissao de ondas sonoras) e equilibrio.',
    localizacao: 'Osso temporal do cranio.',
    irrigacao: 'Arteria labirintica (ramo da basilar).',
    inervacao: 'Nervo vestibulococlear (VIII par craniano).',
    patologias: ['Otite Media', 'Surdez Neurossensorial', 'Vertigem', 'Doenca de Meniere'],
    componentes: [
      { nome: 'Pavilhao Auricular', descricao: 'Orelha externa, capta ondas sonoras' },
      { nome: 'Conduto Auditivo', descricao: 'Canal que conduz som ao timpano' },
      { nome: 'Membrana Timpanica', descricao: 'Vibra com ondas sonoras' },
      { nome: 'Ossiculos (Martelo, Bigorna, Estribo)', descricao: 'Amplificam e transmitem vibracoes' },
      { nome: 'Coclea', descricao: 'Orgao da audicao, converte som em impulso nervoso' },
      { nome: 'Canais Semicirculares', descricao: 'Equilibrio e orientacao espacial' },
    ],
    curiosidade: 'O estribo e o menor osso do corpo humano, com apenas 3 mm.',
  },
];
